# Generated by Django 3.1.3 on 2021-01-26 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_shop', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productcollection',
            name='items',
        ),
        migrations.AddField(
            model_name='productcollection',
            name='items',
            field=models.ManyToManyField(to='online_shop.Product'),
        ),
    ]
